### ISSUE TITLE
running pytest error

### ISSUE THREAD

**Issue by NOrangeeroli** [AdrienC21/CCSD#1]
Hi,
Thanks for your contribution, I tried to run the code but when running the pytests I got the following errors:

```
====================================================================== short test summary info =======================================================================
FAILED tests/utils/test_cc_utils.py::test_cc_incidence_advanced_test - assert False
FAILED tests/utils/test_cc_utils.py::test_mols_to_cc - AssertionError: assert {0: {frozense...'weight': 1}}} == {0: {frozense...'weight': 1}}}
FAILED tests/utils/test_cc_utils.py::test_CC_to_incidence_matrices - assert False
FAILED tests/utils/test_cc_utils.py::test_ccs_to_mol - KeyError: 'symbol'
FAILED tests/utils/test_cc_utils.py::test_convert_CC_to_graphs - AssertionError: assert {0: {'weight'...ght': 1}, ...} == {0: {'symbol'...ght': 1}, ...}
FAILED tests/utils/test_cc_utils.py::test_convert_graphs_to_CCs - AssertionError: assert {'weight': 1} == {'label': 'C', 'weight': 1}
FAILED tests/utils/test_cc_utils.py::test_rank0_distrib_worker - KeyError: 'label_0'
FAILED tests/utils/test_cc_utils.py::test_rank0_distrib_stats - KeyError: 'label_0'
FAILED tests/utils/test_cc_utils.py::test_eval_CC_list - KeyError: 'label_0'
=================================================================== 9 failed, 131 passed in 4.74s ====================================================================

```

Any hints for how to solve this?

Best,
Yamei

**Comment by AdrienC21** [comment]
Hello Yamei!

Thank you for your interest in this project :)

Have you read the "Commons errors" section of the readme? In particular, I believe that your error is related to a dependency issue related to TopoNetX. Have you executed the apply_fixes.py script as explained on the main page? More importantly, did you follow the instructions detailed in the "Error due to TopoNetX when running the tests" subsection?

Let me know if it solves your problem! I remain at your disposal for any further information.

Warm regards,
Adrien

**Comment by NOrangeeroli** [comment]
Dear Adrian, thank you for your prompt reply! This error is now solve by running .github/workflows/apply_fix.py .
